name: "publish"

on:
  push:
    branches:
      - release

jobs:            
  build-tauri:
    permissions:
      contents: write

    env:
      SQLX_OFFLINE: true
      DATABASE_URL: sqlite://db.sqlite

    runs-on: windows-latest  
      
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install frontend dependencies
        run: npm install
       
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-${{ github.sha }}
          releaseName: 'App ${{ github.sha }}'
          releaseDraft: false
          prerelease: false
