name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write

    env:
      DATABASE_URL: sqlite://db.sqlite

    runs-on: windows-latest  
      
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install frontend dependencies
        run: npm install

      - name: Rust chache
        uses: swatinem/rust-cache@v2

      - name: prepare database
        run: |
          cargo install sqlx-cli --no-default-features --features sqlite
          cargo sqlx database create
          cargo sqlx migrate run
        
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
